version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "monthly"
